#!/bin/bash
set -e 

touch ~/.bashrc

git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox ~/content/sct
cd ~/content/sct
yes | ./install_sct
echo 'export PATH=/home/mathieuboudreau/content/sct/bin:$PATH' >> ~/.bashrc
echo 'export MPLBACKEND='Agg'' >> ~/.bashrc
cd ~/